#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import os, sys

KERNEL_SCRIPT="./scripts/debug_ahci_x64.sh"

if __name__ == '__main__':
    print("kconf: Running kernel...")
    os.system(KERNEL_SCRIPT)
    sys.exit(0)

